name: privacy_policy
description: Privacy Policy Page for MakeshTech.

publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
